/**
 * Cross-source insights — the unique value of Revold.
 *
 * These insights are impossible to compute with a single tool because they
 * require joining canonical Revold entities across providers (HubSpot deals,
 * Stripe invoices, Stripe subscriptions, Pipedrive deals, etc.) via the
 * source_links table.
 *
 * All queries are wrapped in try/catch so the page degrades gracefully when
 * the canonical tables haven't been migrated yet or when no data has been
 * ingested for the org.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

export type CrossSourceContext = {
  // Recurring revenue from canonical subscriptions
  totalMrr: number;
  totalArr: number;
  activeSubscriptions: number;
  currency: string;

  // Invoices
  totalInvoices: number;
  paidInvoicesAmount: number;
  unpaidInvoicesCount: number;
  unpaidInvoicesAmount: number;

  // Payments
  failedPaymentsCount: number;
  failedPaymentsAmount: number;

  // Cross-provider entity gaps
  stripeContactsWithoutHubspot: number;
  wonDealsWithoutInvoice: number;
  wonDealsWithoutInvoiceAmount: number;

  // Concentration / top customers
  top5MrrShare: number; // % of total MRR generated by top 5 subscriptions
};

export type CrossSourceInsight = {
  key: string;
  severity: "critical" | "warning" | "info";
  title: string;
  body: string;
  recommendation: string;
};

/**
 * Build the cross-source context. Returns null if the canonical tables don't
 * exist or if no Stripe/Pipedrive ingestion has happened yet.
 */
export async function buildCrossSourceContext(
  supabase: SupabaseClient,
  orgId: string,
): Promise<CrossSourceContext | null> {
  try {
    // Detect if the canonical tables have been migrated by querying source_links
    const { error: probeErr } = await supabase
      .from("source_links")
      .select("id", { count: "exact", head: true })
      .eq("organization_id", orgId)
      .limit(1);
    if (probeErr) return null;
  } catch {
    return null;
  }

  const ctx: CrossSourceContext = {
    totalMrr: 0,
    totalArr: 0,
    activeSubscriptions: 0,
    currency: "EUR",
    totalInvoices: 0,
    paidInvoicesAmount: 0,
    unpaidInvoicesCount: 0,
    unpaidInvoicesAmount: 0,
    failedPaymentsCount: 0,
    failedPaymentsAmount: 0,
    stripeContactsWithoutHubspot: 0,
    wonDealsWithoutInvoice: 0,
    wonDealsWithoutInvoiceAmount: 0,
    top5MrrShare: 0,
  };

  // ── 1. Subscriptions / MRR ────────────────────────────────────
  try {
    const { data: subs } = await supabase
      .from("subscriptions")
      .select("mrr, currency, status")
      .eq("organization_id", orgId)
      .in("status", ["active", "trialing"]);
    if (subs && subs.length > 0) {
      ctx.activeSubscriptions = subs.length;
      const mrrValues = subs.map((s) => Number(s.mrr) || 0).sort((a, b) => b - a);
      ctx.totalMrr = mrrValues.reduce((s, n) => s + n, 0);
      ctx.totalArr = ctx.totalMrr * 12;
      ctx.currency = subs[0].currency || "EUR";
      const top5Sum = mrrValues.slice(0, 5).reduce((s, n) => s + n, 0);
      ctx.top5MrrShare = ctx.totalMrr > 0 ? Math.round((top5Sum / ctx.totalMrr) * 100) : 0;
    }
  } catch {}

  // ── 2. Invoices ───────────────────────────────────────────────
  try {
    const { data: invoices } = await supabase
      .from("invoices")
      .select("status, amount_total, amount_paid, amount_due")
      .eq("organization_id", orgId);
    if (invoices && invoices.length > 0) {
      ctx.totalInvoices = invoices.length;
      for (const inv of invoices) {
        const due = Number(inv.amount_due) || 0;
        const paid = Number(inv.amount_paid) || 0;
        ctx.paidInvoicesAmount += paid;
        if ((inv.status === "open" || inv.status === "uncollectible") && due > 0) {
          ctx.unpaidInvoicesCount++;
          ctx.unpaidInvoicesAmount += due;
        }
      }
    }
  } catch {}

  // ── 3. Failed payments ────────────────────────────────────────
  try {
    const { data: failed } = await supabase
      .from("payments")
      .select("amount")
      .eq("organization_id", orgId)
      .eq("status", "failed");
    if (failed) {
      ctx.failedPaymentsCount = failed.length;
      ctx.failedPaymentsAmount = failed.reduce((s, p) => s + (Number(p.amount) || 0), 0);
    }
  } catch {}

  // ── 4. Stripe contacts without HubSpot link ───────────────────
  try {
    const { data: stripeLinks } = await supabase
      .from("source_links")
      .select("internal_id")
      .eq("organization_id", orgId)
      .eq("provider", "stripe")
      .eq("entity_type", "contact");
    const stripeContactIds = (stripeLinks ?? []).map((l) => l.internal_id as string);
    if (stripeContactIds.length > 0) {
      // Batch in chunks of 200 to keep the IN clause manageable
      const chunkSize = 200;
      for (let i = 0; i < stripeContactIds.length; i += chunkSize) {
        const chunk = stripeContactIds.slice(i, i + chunkSize);
        const { count } = await supabase
          .from("contacts")
          .select("*", { count: "exact", head: true })
          .eq("organization_id", orgId)
          .in("id", chunk)
          .is("hubspot_id", null);
        ctx.stripeContactsWithoutHubspot += count ?? 0;
      }
    }
  } catch {}

  // ── 5. Won deals without invoice (revenue leakage) ────────────
  try {
    const { data: wonDeals } = await supabase
      .from("deals")
      .select("id, company_id, amount")
      .eq("organization_id", orgId)
      .eq("is_closed_won", true)
      .not("company_id", "is", null);
    if (wonDeals && wonDeals.length > 0) {
      const wonCompanyIds = Array.from(
        new Set(wonDeals.map((d) => d.company_id as string)),
      );
      const invoicedSet = new Set<string>();
      const chunkSize = 200;
      for (let i = 0; i < wonCompanyIds.length; i += chunkSize) {
        const chunk = wonCompanyIds.slice(i, i + chunkSize);
        const { data: rows } = await supabase
          .from("invoices")
          .select("company_id")
          .eq("organization_id", orgId)
          .in("company_id", chunk);
        (rows ?? []).forEach((r) => r.company_id && invoicedSet.add(r.company_id as string));
      }
      for (const d of wonDeals) {
        if (!invoicedSet.has(d.company_id as string)) {
          ctx.wonDealsWithoutInvoice++;
          ctx.wonDealsWithoutInvoiceAmount += Number(d.amount) || 0;
        }
      }
    }
  } catch {}

  // Return null if absolutely nothing was found — keeps the UI clean
  const hasAnyData =
    ctx.activeSubscriptions > 0 ||
    ctx.totalInvoices > 0 ||
    ctx.failedPaymentsCount > 0 ||
    ctx.stripeContactsWithoutHubspot > 0;
  if (!hasAnyData) return null;

  return ctx;
}

/**
 * Format an amount in the user's currency.
 */
function fmtMoney(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat("fr-FR", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `${Math.round(amount).toLocaleString("fr-FR")} ${currency}`;
  }
}

/**
 * Generate cross-source insights from the context.
 * Filters out insights that the user has already dismissed.
 */
export function selectCrossSourceInsights(
  ctx: CrossSourceContext,
  dismissedKeys: Set<string>,
): CrossSourceInsight[] {
  const insights: CrossSourceInsight[] = [];

  // 1. Revenue leakage — won deals without invoice
  if (ctx.wonDealsWithoutInvoice > 0) {
    insights.push({
      key: "cross_revenue_leakage",
      severity: "critical",
      title: `🔗 Fuite revenue : ${ctx.wonDealsWithoutInvoice} deals gagnés sans facture associée`,
      body: `${ctx.wonDealsWithoutInvoice} deals HubSpot sont marqués "Closed Won" mais aucune facture correspondante n'a été détectée dans Stripe / Pennylane. Montant cumulé estimé : ${fmtMoney(ctx.wonDealsWithoutInvoiceAmount, ctx.currency)}.`,
      recommendation: `Vérifier ces deals avec l'équipe finance — soit la facturation n'a pas été déclenchée (perte sèche), soit le rapprochement HubSpot ↔ Stripe doit être ajusté. C'est la priorité #1 pour récupérer du CA déjà signé.`,
    });
  }

  // 2. Failed payments — alerte CSM
  if (ctx.failedPaymentsCount > 0) {
    insights.push({
      key: "cross_failed_payments",
      severity: "critical",
      title: `🔗 ${ctx.failedPaymentsCount} paiements en échec détectés`,
      body: `Stripe a enregistré ${ctx.failedPaymentsCount} paiements échoués pour un total de ${fmtMoney(ctx.failedPaymentsAmount, ctx.currency)}. Ces clients sont en risque de churn immédiat.`,
      recommendation: `Lancer une action CSM proactive : email de relance + appel sur les comptes Tier 1 dans les 24h. Sans intervention, ces customers entreront en past_due puis cancel.`,
    });
  }

  // 3. Unpaid invoices
  if (ctx.unpaidInvoicesCount > 0) {
    insights.push({
      key: "cross_unpaid_invoices",
      severity: "warning",
      title: `🔗 ${ctx.unpaidInvoicesCount} factures impayées (${fmtMoney(ctx.unpaidInvoicesAmount, ctx.currency)})`,
      body: `${ctx.unpaidInvoicesCount} factures sont ouvertes ou en uncollectible avec un montant dû. Total : ${fmtMoney(ctx.unpaidInvoicesAmount, ctx.currency)}.`,
      recommendation: `Croiser cette liste avec les owners commerciaux dans HubSpot pour des relances ciblées. Les factures > 30j devraient remonter en alerte.`,
    });
  }

  // 4. Stripe customers orphelins en HubSpot
  if (ctx.stripeContactsWithoutHubspot > 0) {
    insights.push({
      key: "cross_stripe_orphans",
      severity: "warning",
      title: `🔗 ${ctx.stripeContactsWithoutHubspot} customers Stripe sans contact HubSpot`,
      body: `Ces clients facturés via Stripe n'ont jamais été synchronisés dans HubSpot. Personne ne les suit côté commercial — angle mort total sur l'expansion, l'upsell ou la rétention.`,
      recommendation: `Importer ces contacts dans HubSpot (Revold peut le faire en push back) et leur assigner un owner. Chaque customer Stripe DOIT avoir un référent commercial.`,
    });
  }

  // 5. MRR ingéré (positive insight)
  if (ctx.totalMrr > 0) {
    insights.push({
      key: "cross_mrr_baseline",
      severity: "info",
      title: `🔗 ${fmtMoney(ctx.totalMrr, ctx.currency)} de MRR centralisé dans Revold (${fmtMoney(ctx.totalArr, ctx.currency)} ARR)`,
      body: `${ctx.activeSubscriptions} abonnements actifs ingérés depuis Stripe. C'est votre revenu récurrent réel — à comparer avec le forecast HubSpot pour mesurer l'écart prévision / réalité.`,
      recommendation: `Activer le rapport "Forecast HubSpot vs MRR Stripe" dans la page Rapports pour voir l'écart sur les 12 derniers mois.`,
    });
  }

  // 6. Concentration risk — top 5 > 50%
  if (ctx.top5MrrShare >= 50 && ctx.activeSubscriptions >= 5) {
    insights.push({
      key: "cross_mrr_concentration",
      severity: "warning",
      title: `🔗 Concentration revenue : top 5 customers = ${ctx.top5MrrShare}% du MRR`,
      body: `Vos 5 plus gros clients représentent ${ctx.top5MrrShare}% du MRR total. Risque business élevé : la perte d'un seul de ces comptes ferait chuter votre revenue récurrent significativement.`,
      recommendation: `Mettre en place un programme Key Account Management dédié sur ces comptes. Tag "Tier 1" dans HubSpot, revue trimestrielle, sponsor exécutif côté Revold.`,
    });
  }

  return insights.filter((i) => !dismissedKeys.has(i.key));
}
