/**
 * Cross-source insights — the unique value of Revold.
 *
 * These insights are impossible to compute with a single tool because they
 * require joining canonical Revold entities across providers (HubSpot deals,
 * Stripe invoices, Stripe subscriptions, Pipedrive deals, etc.) via the
 * source_links table.
 *
 * All queries are wrapped in try/catch so the page degrades gracefully when
 * the canonical tables haven't been migrated yet or when no data has been
 * ingested for the org.
 */

import type { SupabaseClient } from "@supabase/supabase-js";

export type CrossSourceContext = {
  // Recurring revenue from canonical subscriptions
  totalMrr: number;
  totalArr: number;
  activeSubscriptions: number;
  currency: string;

  // Invoices
  totalInvoices: number;
  paidInvoicesAmount: number;
  unpaidInvoicesCount: number;
  unpaidInvoicesAmount: number;

  // Payments
  failedPaymentsCount: number;
  failedPaymentsAmount: number;

  // Cross-provider entity gaps
  stripeContactsWithoutHubspot: number;
  wonDealsWithoutInvoice: number;
  wonDealsWithoutInvoiceAmount: number;

  // Concentration / top customers
  top5MrrShare: number; // % of total MRR generated by top 5 subscriptions
};

export type CrossSourceInsight = {
  key: string;
  severity: "critical" | "warning" | "info";
  title: string;
  body: string;
  recommendation: string;
  /** Catégories d'outils Revold requises pour que cet insight soit pertinent. */
  requires?: Array<"billing" | "support" | "phone" | "conv_intel" | "communication">;
};

/**
 * Set des catégories d'outils que l'org a connectées dans Revold (table
 * integrations). Sert à filtrer les insights/sims qui inventeraient de la
 * donnée sur des outils absents.
 */
export type ConnectedCategorySet = Set<"crm" | "billing" | "support" | "phone" | "conv_intel" | "communication">;

/**
 * Build the cross-source context. Returns null if the canonical tables don't
 * exist or if no Stripe/Pipedrive ingestion has happened yet.
 */
export async function buildCrossSourceContext(
  supabase: SupabaseClient,
  orgId: string,
): Promise<CrossSourceContext | null> {
  try {
    // Detect if the canonical tables have been migrated by querying source_links
    const { error: probeErr } = await supabase
      .from("source_links")
      .select("id", { count: "exact", head: true })
      .eq("organization_id", orgId)
      .limit(1);
    if (probeErr) return null;
  } catch {
    return null;
  }

  const ctx: CrossSourceContext = {
    totalMrr: 0,
    totalArr: 0,
    activeSubscriptions: 0,
    currency: "EUR",
    totalInvoices: 0,
    paidInvoicesAmount: 0,
    unpaidInvoicesCount: 0,
    unpaidInvoicesAmount: 0,
    failedPaymentsCount: 0,
    failedPaymentsAmount: 0,
    stripeContactsWithoutHubspot: 0,
    wonDealsWithoutInvoice: 0,
    wonDealsWithoutInvoiceAmount: 0,
    top5MrrShare: 0,
  };

  // ── 1. Subscriptions / MRR ────────────────────────────────────
  try {
    const { data: subs } = await supabase
      .from("subscriptions")
      .select("mrr, currency, status")
      .eq("organization_id", orgId)
      .in("status", ["active", "trialing"]);
    if (subs && subs.length > 0) {
      ctx.activeSubscriptions = subs.length;
      const mrrValues = subs.map((s) => Number(s.mrr) || 0).sort((a, b) => b - a);
      ctx.totalMrr = mrrValues.reduce((s, n) => s + n, 0);
      ctx.totalArr = ctx.totalMrr * 12;
      ctx.currency = subs[0].currency || "EUR";
      const top5Sum = mrrValues.slice(0, 5).reduce((s, n) => s + n, 0);
      ctx.top5MrrShare = ctx.totalMrr > 0 ? Math.round((top5Sum / ctx.totalMrr) * 100) : 0;
    }
  } catch {}

  // ── 2. Invoices ───────────────────────────────────────────────
  try {
    const { data: invoices } = await supabase
      .from("invoices")
      .select("status, amount_total, amount_paid, amount_due")
      .eq("organization_id", orgId);
    if (invoices && invoices.length > 0) {
      ctx.totalInvoices = invoices.length;
      for (const inv of invoices) {
        const due = Number(inv.amount_due) || 0;
        const paid = Number(inv.amount_paid) || 0;
        ctx.paidInvoicesAmount += paid;
        if ((inv.status === "open" || inv.status === "uncollectible") && due > 0) {
          ctx.unpaidInvoicesCount++;
          ctx.unpaidInvoicesAmount += due;
        }
      }
    }
  } catch {}

  // ── 3. Failed payments ────────────────────────────────────────
  try {
    const { data: failed } = await supabase
      .from("payments")
      .select("amount")
      .eq("organization_id", orgId)
      .eq("status", "failed");
    if (failed) {
      ctx.failedPaymentsCount = failed.length;
      ctx.failedPaymentsAmount = failed.reduce((s, p) => s + (Number(p.amount) || 0), 0);
    }
  } catch {}

  // ── 4. Stripe contacts without HubSpot link ───────────────────
  try {
    const { data: stripeLinks } = await supabase
      .from("source_links")
      .select("internal_id")
      .eq("organization_id", orgId)
      .eq("provider", "stripe")
      .eq("entity_type", "contact");
    const stripeContactIds = (stripeLinks ?? []).map((l) => l.internal_id as string);
    if (stripeContactIds.length > 0) {
      // Batch in chunks of 200 to keep the IN clause manageable
      const chunkSize = 200;
      for (let i = 0; i < stripeContactIds.length; i += chunkSize) {
        const chunk = stripeContactIds.slice(i, i + chunkSize);
        const { count } = await supabase
          .from("contacts")
          .select("*", { count: "exact", head: true })
          .eq("organization_id", orgId)
          .in("id", chunk)
          .is("hubspot_id", null);
        ctx.stripeContactsWithoutHubspot += count ?? 0;
      }
    }
  } catch {}

  // ── 5. Won deals without invoice (revenue leakage) ────────────
  try {
    const { data: wonDeals } = await supabase
      .from("deals")
      .select("id, company_id, amount")
      .eq("organization_id", orgId)
      .eq("is_closed_won", true)
      .not("company_id", "is", null);
    if (wonDeals && wonDeals.length > 0) {
      const wonCompanyIds = Array.from(
        new Set(wonDeals.map((d) => d.company_id as string)),
      );
      const invoicedSet = new Set<string>();
      const chunkSize = 200;
      for (let i = 0; i < wonCompanyIds.length; i += chunkSize) {
        const chunk = wonCompanyIds.slice(i, i + chunkSize);
        const { data: rows } = await supabase
          .from("invoices")
          .select("company_id")
          .eq("organization_id", orgId)
          .in("company_id", chunk);
        (rows ?? []).forEach((r) => r.company_id && invoicedSet.add(r.company_id as string));
      }
      for (const d of wonDeals) {
        if (!invoicedSet.has(d.company_id as string)) {
          ctx.wonDealsWithoutInvoice++;
          ctx.wonDealsWithoutInvoiceAmount += Number(d.amount) || 0;
        }
      }
    }
  } catch {}

  // ⚠ On retourne TOUJOURS le contexte (même vide) pour que les always-on
  // insights cross-source s'affichent comme conseils RevOps universels.
  // Les insights conditionnels ne fireront que si la donnée est présente.
  return ctx;
}

/**
 * Format an amount in the user's currency.
 */
function fmtMoney(amount: number, currency: string): string {
  try {
    return new Intl.NumberFormat("fr-FR", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `${Math.round(amount).toLocaleString("fr-FR")} ${currency}`;
  }
}

/**
 * Generate cross-source insights from the context.
 * Filters out insights that the user has already dismissed.
 *
 * `connected` (optionnel) : catégories d'outils branchées à Revold. Si fourni,
 * les insights `requires` non couverts sont exclus pour ne pas inventer de la
 * donnée. À la place, un seul CTA explicite par catégorie manquante est ajouté
 * en queue (cross_connect_*).
 */
export function selectCrossSourceInsights(
  ctx: CrossSourceContext,
  dismissedKeys: Set<string>,
  connected?: ConnectedCategorySet,
): CrossSourceInsight[] {
  const insights: CrossSourceInsight[] = [];

  // 1. Revenue leakage — won deals without invoice
  if (ctx.wonDealsWithoutInvoice > 0) {
    insights.push({
      key: "cross_revenue_leakage",
      severity: "critical",
      title: `🔗 Fuite revenue : ${ctx.wonDealsWithoutInvoice} deals gagnés sans facture associée`,
      body: `${ctx.wonDealsWithoutInvoice} deals HubSpot sont marqués "Closed Won" mais aucune facture correspondante n'a été détectée dans Stripe / Pennylane. Montant cumulé estimé : ${fmtMoney(ctx.wonDealsWithoutInvoiceAmount, ctx.currency)}.`,
      recommendation: `Vérifier ces deals avec l'équipe finance — soit la facturation n'a pas été déclenchée (perte sèche), soit le rapprochement HubSpot ↔ Stripe doit être ajusté. C'est la priorité #1 pour récupérer du CA déjà signé.`,
    });
  }

  // 2. Failed payments — alerte CSM
  if (ctx.failedPaymentsCount > 0) {
    insights.push({
      key: "cross_failed_payments",
      severity: "critical",
      title: `🔗 ${ctx.failedPaymentsCount} paiements en échec détectés`,
      body: `Stripe a enregistré ${ctx.failedPaymentsCount} paiements échoués pour un total de ${fmtMoney(ctx.failedPaymentsAmount, ctx.currency)}. Ces clients sont en risque de churn immédiat.`,
      recommendation: `Lancer une action CSM proactive : email de relance + appel sur les comptes Tier 1 dans les 24h. Sans intervention, ces customers entreront en past_due puis cancel.`,
    });
  }

  // 3. Unpaid invoices
  if (ctx.unpaidInvoicesCount > 0) {
    insights.push({
      key: "cross_unpaid_invoices",
      severity: "warning",
      title: `🔗 ${ctx.unpaidInvoicesCount} factures impayées (${fmtMoney(ctx.unpaidInvoicesAmount, ctx.currency)})`,
      body: `${ctx.unpaidInvoicesCount} factures sont ouvertes ou en uncollectible avec un montant dû. Total : ${fmtMoney(ctx.unpaidInvoicesAmount, ctx.currency)}.`,
      recommendation: `Croiser cette liste avec les owners commerciaux dans HubSpot pour des relances ciblées. Les factures > 30j devraient remonter en alerte.`,
    });
  }

  // 4. Stripe customers orphelins en HubSpot
  if (ctx.stripeContactsWithoutHubspot > 0) {
    insights.push({
      key: "cross_stripe_orphans",
      severity: "warning",
      title: `🔗 ${ctx.stripeContactsWithoutHubspot} customers Stripe sans contact HubSpot`,
      body: `Ces clients facturés via Stripe n'ont jamais été synchronisés dans HubSpot. Personne ne les suit côté commercial — angle mort total sur l'expansion, l'upsell ou la rétention.`,
      recommendation: `Importer ces contacts dans HubSpot (Revold peut le faire en push back) et leur assigner un owner. Chaque customer Stripe DOIT avoir un référent commercial.`,
    });
  }

  // 5. MRR ingéré (positive insight)
  if (ctx.totalMrr > 0) {
    insights.push({
      key: "cross_mrr_baseline",
      severity: "info",
      title: `🔗 ${fmtMoney(ctx.totalMrr, ctx.currency)} de MRR centralisé dans Revold (${fmtMoney(ctx.totalArr, ctx.currency)} ARR)`,
      body: `${ctx.activeSubscriptions} abonnements actifs ingérés depuis Stripe. C'est votre revenu récurrent réel — à comparer avec le forecast HubSpot pour mesurer l'écart prévision / réalité.`,
      recommendation: `Activer le rapport "Forecast HubSpot vs MRR Stripe" dans la page Rapports pour voir l'écart sur les 12 derniers mois.`,
    });
  }

  // 6. Concentration risk — top 5 > 50%
  if (ctx.top5MrrShare >= 50 && ctx.activeSubscriptions >= 5) {
    insights.push({
      key: "cross_mrr_concentration",
      severity: "warning",
      title: `🔗 Concentration revenue : top 5 customers = ${ctx.top5MrrShare}% du MRR`,
      body: `Vos 5 plus gros clients représentent ${ctx.top5MrrShare}% du MRR total. Risque business élevé : la perte d'un seul de ces comptes ferait chuter votre revenue récurrent significativement.`,
      recommendation: `Mettre en place un programme Key Account Management dédié sur ces comptes. Tag "Tier 1" dans HubSpot, revue trimestrielle, sponsor exécutif côté Revold.`,
    });
  }

  // ── ALWAYS-ON cross-source recommendations ──
  // Chaque item est tagué avec `requires` : les catégories d'outils Revold
  // nécessaires pour que la recommandation soit pertinente. Si l'org n'a pas
  // l'outil branché, on n'invente PAS la donnée — on remplace par un CTA.
  insights.push(
    {
      key: "cross_forecast_vs_billing",
      severity: "info",
      title: "🔗 Réconcilier forecast HubSpot vs facturation réelle",
      body: "Le forecast pipeline et le CA encaissé Stripe/Pennylane divergent souvent de 10-30%. Sans réconciliation, on pilote sur un forecast déconnecté du cash réel.",
      recommendation: "Activer le rapport « Forecast HubSpot vs CA encaissé » qui matche les deals gagnés à leurs factures. Audit mensuel des écarts > 5%.",
      requires: ["billing"],
    },
    {
      key: "cross_csm_account_health",
      severity: "info",
      title: "🔗 Account health score multi-sources",
      body: "Combiner usage produit + tickets support + factures impayées + sentiment NPS donne un score de santé client bien plus fiable qu'un signal seul.",
      recommendation: "Construire un score composite dans Revold avec 4-5 inputs cross-source. Alertes proactives sur les comptes qui dégradent leur score.",
      requires: ["billing", "support"],
    },
    {
      key: "cross_quote_to_invoice_speed",
      severity: "info",
      title: "🔗 Mesurer le délai devis → facture",
      body: "Plus le cycle quote→invoice est long, plus le DSO augmente. Un cycle court accélère le cash et révèle les frictions process.",
      recommendation: "Croiser dates devis HubSpot et émission facture Stripe. Cible : < 5 jours pour les < 5k€, < 15 jours pour les comptes complexes.",
      requires: ["billing"],
    },
    {
      key: "cross_churn_signals",
      severity: "info",
      title: "🔗 Détection churn multi-signaux",
      body: "Le churn se prédit avec 3-4 signaux faibles : baisse usage, augmentation tickets, retard paiement, NPS détracteur. Aucun outil seul ne voit l'ensemble.",
      recommendation: "Workflow Revold qui agrège les signaux et flagge les comptes en zone risque. Notification CSM 60 jours avant renouvellement à risque.",
      requires: ["support", "billing"],
    },
    {
      key: "cross_expansion_signals",
      severity: "info",
      title: "🔗 Détection expansion multi-signaux",
      body: "Les comptes prêts pour l'upsell ont des patterns : usage croissant + nombre d'utilisateurs additionnés + activations features avancées + NPS promoteur.",
      recommendation: "Créer un scoring expansion qui combine ces inputs. Workflow d'attribution automatique au CSM expansion sur les top scorers.",
      requires: ["billing"],
    },
    {
      key: "cross_attribution_revenue",
      severity: "info",
      title: "🔗 Attribution revenue multi-touch",
      body: "Sans cross-source, l'attribution se fait sur le dernier touch (souvent direct). On surévalue le brand au détriment des canaux d'acquisition réels.",
      recommendation: "Construire un modèle d'attribution multi-touch en croisant marketing campaigns + leads + deals + revenue. Revoir l'allocation budget mensuellement.",
      requires: ["billing"],
    },
    {
      key: "cross_data_completeness_audit",
      severity: "info",
      title: "🔗 Audit de complétude data inter-outils",
      body: "Chaque tool a sa source de vérité : HubSpot pour le CRM, Stripe pour le revenue, Zendesk pour le support. Sans audit, des trous se créent.",
      recommendation: "Créer un dashboard Revold qui montre, pour chaque entité (compte, contact, deal), si elle existe dans tous les tools attendus. Alertes sur les manquants.",
      // Pertinent dès qu'on a un 2e outil connecté en plus du CRM.
      requires: ["billing"],
    },
    {
      key: "cross_unified_customer_view",
      severity: "info",
      title: "🔗 Vue client unifiée 360°",
      body: "Sans vue unifiée, les équipes consultent 5 outils pour comprendre un client. Friction massive + risque d'erreur (versions différentes).",
      recommendation: "Construire une fiche client Revold qui agrège : deals HubSpot + paiements Stripe + tickets Zendesk + activité produit. Source de vérité unique.",
      requires: ["billing", "support"],
    },
    {
      key: "cross_sales_finance_alignment",
      severity: "info",
      title: "🔗 Aligner sales et finance sur la définition d'un deal gagné",
      body: "Sales considère un deal gagné = signature contrat. Finance = première facture émise. Cet écart explique 80% des conflits forecast vs CA.",
      recommendation: "Réunion sales + finance pour figer une définition commune. Workflow HubSpot qui ne marque « won » qu'à émission de la 1ʳᵉ facture.",
      requires: ["billing"],
    },
    {
      key: "cross_data_warehouse",
      severity: "info",
      title: "🔗 Stocker l'historique cross-source dans un entrepôt",
      body: "Les outils SaaS ont des historiques limités (90j, 1an). Pour analyser sur > 1 an, il faut un entrepôt (BigQuery, Snowflake, Postgres dédié).",
      recommendation: "Brancher un connecteur Fivetran/Airbyte vers BigQuery/Snowflake. Revold devient le tableau de bord, l'entrepôt garde la mémoire long terme.",
      requires: ["billing"],
    },
    {
      key: "cross_attribution_offline",
      severity: "info",
      title: "🔗 Réintégrer les revenus offline (factures papier, virements)",
      body: "Beaucoup de B2B ont 30-50% de CA offline (factures papier, virements directs). Sans réintégration, l'attribution est faussée.",
      recommendation: "Process mensuel d'import des factures non-Stripe (depuis l'ERP ou Pennylane). Tag « offline » pour les distinguer dans les rapports.",
      requires: ["billing"],
    },
    {
      key: "cross_sla_response_times",
      severity: "info",
      title: "🔗 Mesurer les SLA inter-équipes (sales, support, success)",
      body: "Les délais de réponse impactent la conversion lead, la santé client, le NPS. Mesurés à l'échelle équipe, ils révèlent les goulots.",
      recommendation: "Définir des SLAs : < 5min pour un lead chaud, < 4h pour un ticket support, < 24h pour un email customer. Reporting hebdo.",
      requires: ["support"],
    },
    {
      key: "cross_renewal_health",
      severity: "info",
      title: "🔗 Health score renouvellement à 90 jours",
      body: "Le renouvellement se prépare 90 jours avant l'échéance. Un score combinant usage, tickets, NPS et discussions sales prédit le risque.",
      recommendation: "Créer le score auto dans Revold. CSM alerté dès que le score d'un compte franchit le seuil rouge. Action playbook standardisée.",
      requires: ["billing", "support"],
    },
    {
      key: "cross_compliance_data_residency",
      severity: "info",
      title: "🔗 Audit RGPD inter-outils",
      body: "Un contact peut être supprimé dans HubSpot mais persister dans Stripe, Mailchimp, Calendly. Le droit à l'oubli est cassé sans process cross-source.",
      recommendation: "Workflow Revold de droit à l'oubli qui propage la suppression à tous les outils connectés. Audit trimestriel des écarts.",
      requires: ["billing"],
    },
  );

  // ── Filtrage gating + CTA pour chaque catégorie manquante ──
  let filtered = insights;
  if (connected) {
    filtered = insights.filter((i) => {
      if (!i.requires || i.requires.length === 0) return true;
      // Garder uniquement si TOUTES les catégories requises sont connectées
      return i.requires.every((req) => connected.has(req));
    });

    const missingCategories = MISSING_CTA_ORDER.filter((cat) => !connected.has(cat));
    for (const cat of missingCategories) {
      const cta = MISSING_CATEGORY_CTAS[cat];
      filtered.push(cta);
    }
  }

  return filtered.filter((i) => !dismissedKeys.has(i.key));
}

// ── CTAs par catégorie d'outil manquante ──────────────────────────────
const MISSING_CTA_ORDER: Array<"billing" | "support" | "phone" | "conv_intel" | "communication"> = [
  "billing",
  "support",
  "phone",
  "conv_intel",
  "communication",
];

const MISSING_CATEGORY_CTAS: Record<
  "billing" | "support" | "phone" | "conv_intel" | "communication",
  CrossSourceInsight
> = {
  billing: {
    key: "cross_connect_billing",
    severity: "info",
    title: "🔌 Connectez un outil de facturation pour débloquer 11 insights",
    body: "Sans Stripe / Pennylane / Sellsy / Axonaut / QuickBooks branché, les insights revenue (MRR, churn, fuite revenue, DSO, attribution) ne peuvent pas être calculés. Aucune donnée n'est inventée tant qu'aucun outil de facturation n'est connecté.",
    recommendation: "Allez dans Intégrations → catégorie Facturation et connectez votre outil. Les insights cross-source apparaîtront automatiquement.",
  },
  support: {
    key: "cross_connect_support",
    severity: "info",
    title: "🔌 Connectez un outil de service client pour débloquer 5 insights",
    body: "Sans Intercom / Zendesk / Crisp / Freshdesk branché, les insights santé client (account health, churn signals, SLA, renewal) ne peuvent pas être calculés.",
    recommendation: "Allez dans Intégrations → catégorie Service client et connectez votre outil de support. Les coachings cross-source santé client apparaîtront automatiquement.",
  },
  phone: {
    key: "cross_connect_phone",
    severity: "info",
    title: "🔌 Connectez un outil de téléphonie pour mesurer l'impact appels",
    body: "Sans Aircall / Ringover branché, impossible de croiser les appels avec les deals pour mesurer l'impact du téléphone sur le closing rate.",
    recommendation: "Allez dans Intégrations → catégorie Téléphonie. Les coachings appels × pipeline arriveront dès la connexion.",
  },
  conv_intel: {
    key: "cross_connect_conv_intel",
    severity: "info",
    title: "🔌 Connectez Praiz pour analyser vos conversations commerciales",
    body: "Sans conversation intelligence (Praiz), les insights talk ratio × win rate, objections récurrentes et scoring deal automatique ne sont pas disponibles.",
    recommendation: "Allez dans Intégrations → Praiz. Configurez le webhook secret puis branchez le webhook côté Praiz pour activer la synchro.",
  },
  communication: {
    key: "cross_connect_communication",
    severity: "info",
    title: "🔌 Connectez un canal Slack / Teams / email pour recevoir vos alertes",
    body: "Sans canal de communication branché, les alertes critiques et le digest quotidien Revold restent uniquement consultables in-app.",
    recommendation: "Allez dans Intégrations → catégorie Communication et choisissez Slack, Teams, Gmail ou Outlook.",
  },
};
