/**
 * Glossaire RevOps / Revenue Intelligence — définitions courtes, précises et
 * citables (une à trois phrases), avec formule quand il y en a une. Chaque
 * terme a une ancre (#slug) et une entrée DefinedTerm en JSON-LD : c'est le
 * format que les moteurs génératifs reprennent le plus volontiers.
 */

export type GlossaryTerm = {
  slug: string;
  term: string;
  /** Variantes / traductions recherchées. */
  aliases?: string[];
  definition: string;
  formula?: string;
  /** Page du site qui approfondit le sujet. */
  link?: { href: string; label: string };
};

export const GLOSSARY: GlossaryTerm[] = [
  { slug: "revops", term: "RevOps (Revenue Operations)", aliases: ["Revenue Operations"], definition: "Fonction et méthode qui alignent marketing, ventes, service client et finance sur un même processus de revenu, avec des données, des indicateurs et des objectifs partagés. Le RevOps traite le revenu comme un flux continu, du lead à l'encaissement.", link: { href: "/plateforme-revops", label: "Plateforme RevOps" } },
  { slug: "revenue-intelligence", term: "Revenue Intelligence", definition: "Exploitation automatique des données de revenu (CRM, facturation, support, banque, activité commerciale) pour prévoir le chiffre d'affaires, détecter les risques et recommander des actions.", link: { href: "/revenue-intelligence", label: "Revenue Intelligence : guide" } },
  { slug: "sales-ops", term: "Sales Ops (Sales Operations)", definition: "Fonction qui outille et optimise l'équipe commerciale : processus de vente, CRM, reporting du pipeline, quotas. C'est une composante du RevOps, limitée aux ventes.", link: { href: "/revops-vs-sales-ops", label: "RevOps vs Sales Ops" } },
  { slug: "pipeline", term: "Pipeline commercial", definition: "Ensemble des opportunités (deals) ouvertes, organisées par étapes de vente. Sa valeur est la somme des montants des deals ouverts ; sa valeur pondérée applique la probabilité de chaque étape." },
  { slug: "forecast", term: "Forecast commercial", aliases: ["prévision des ventes"], definition: "Prévision du chiffre d'affaires attendu sur une période, calculée à partir du pipeline (montant, probabilité d'étape, date de fermeture) et confrontée au réalisé.", formula: "Forecast pondéré = Σ (montant du deal × probabilité de l'étape), pour les deals dont la date de fermeture tombe dans la période", link: { href: "/forecast-commercial", label: "Forecast commercial" } },
  { slug: "forecast-pondere", term: "Forecast pondéré", definition: "Forecast dans lequel chaque deal compte pour son montant multiplié par la probabilité de son étape de pipeline, plutôt que pour son montant entier.", formula: "Σ montant × probabilité d'étape" },
  { slug: "precision-du-forecast", term: "Précision du forecast", aliases: ["forecast accuracy"], definition: "Rapport entre le revenu réellement signé sur une période et le forecast annoncé au début de cette période. Un indicateur RevOps central : il mesure la fiabilité du pipeline.", formula: "Précision = signé réel ÷ forecast annoncé × 100" },
  { slug: "date-de-fermeture", term: "Date de fermeture (close date)", definition: "Date prévue de signature d'un deal, portée par la propriété closedate dans HubSpot. Elle détermine dans quelle période le deal est compté au forecast ; une date non maintenue fausse toute prévision." },
  { slug: "deal-stagnant", term: "Deal stagnant", definition: "Opportunité ouverte restée dans la même étape de pipeline au-delà d'un seuil de jours (souvent 14 à 30). Signal de risque de perte silencieuse ou de pipeline gonflé." },
  { slug: "taux-de-conversion-par-etape", term: "Taux de conversion par étape", definition: "Part des deals entrés dans une étape qui passent à l'étape suivante. C'est l'indicateur le plus actionnable du pipeline : il localise les goulots d'étranglement.", formula: "Deals passés à l'étape suivante ÷ deals entrés dans l'étape" },
  { slug: "cycle-de-vente", term: "Cycle de vente", definition: "Délai moyen entre la création d'un deal et sa signature, mesuré sur les deals gagnés. Il conditionne la vélocité du pipeline et le besoin de trésorerie." },
  { slug: "velocite-du-pipeline", term: "Vélocité du pipeline", definition: "Vitesse à laquelle le pipeline génère du revenu, combinant nombre de deals, panier moyen, taux de closing et cycle de vente.", formula: "(nombre de deals × panier moyen × taux de closing) ÷ cycle de vente en jours" },
  { slug: "mql", term: "MQL (Marketing Qualified Lead)", definition: "Contact que le marketing juge suffisamment qualifié pour être transmis aux ventes, selon des critères de scoring ou de comportement. Dans HubSpot, matérialisé par l'étape de cycle de vie marketingqualifiedlead." },
  { slug: "sql", term: "SQL (Sales Qualified Lead)", definition: "Contact ou compte que les ventes ont qualifié comme opportunité réelle après un premier échange. Le taux MQL → SQL mesure l'alignement marketing – ventes." },
  { slug: "cycle-de-vie", term: "Cycle de vie (lifecycle stage)", definition: "Étapes successives d'un contact ou d'une entreprise dans HubSpot : abonné, lead, MQL, SQL, opportunité, client, ambassadeur. Les dates d'entrée dans chaque étape permettent de mesurer les délais de conversion." },
  { slug: "cout-par-lead", term: "Coût par lead (CPL)", definition: "Dépense d'acquisition rapportée au nombre de leads générés sur la période, par canal ou par campagne.", formula: "Dépense publicitaire ÷ leads générés" },
  { slug: "mrr", term: "MRR (Monthly Recurring Revenue)", aliases: ["revenu mensuel récurrent"], definition: "Somme du revenu récurrent mensuel de tous les abonnements actifs, hors revenus ponctuels. Indicateur central des modèles à abonnement.", formula: "MRR = Σ revenu mensuel des abonnements actifs ; ARR = MRR × 12", link: { href: "/outils/calculateur-mrr", label: "Calculateur MRR" } },
  { slug: "arr", term: "ARR (Annual Recurring Revenue)", definition: "Revenu récurrent annualisé : le MRR multiplié par douze, ou la somme des contrats annuels actifs.", formula: "ARR = MRR × 12" },
  { slug: "net-new-mrr", term: "Net New MRR", definition: "Variation nette du MRR sur une période, combinant nouveaux clients, expansion, contraction et churn.", formula: "Net New MRR = nouveau MRR + expansion − contraction − churn" },
  { slug: "churn", term: "Churn (taux d'attrition)", definition: "Part des clients (churn client) ou du revenu récurrent (churn revenu) perdue sur une période. Le churn revenu pondère par le montant : perdre un gros compte pèse plus que perdre trois petits.", formula: "Churn client = clients perdus ÷ clients en début de période ; churn revenu = MRR perdu ÷ MRR en début de période", link: { href: "/outils/calculateur-churn", label: "Calculateur de churn" } },
  { slug: "nrr", term: "Rétention nette (NRR)", aliases: ["Net Revenue Retention"], definition: "Part du revenu récurrent d'une cohorte de clients conservée un an plus tard, expansion incluse. Au-dessus de 100 %, la base existante croît sans nouveaux clients.", formula: "NRR = (MRR initial + expansion − contraction − churn) ÷ MRR initial" },
  { slug: "ltv", term: "LTV (valeur vie client)", aliases: ["CLV", "customer lifetime value"], definition: "Revenu total attendu d'un client sur la durée de la relation. Une approximation courante divise le revenu mensuel moyen par client par le taux de churn mensuel.", formula: "LTV ≈ ARPA mensuel ÷ churn mensuel" },
  { slug: "cac", term: "CAC (coût d'acquisition client)", definition: "Dépense totale de marketing et de vente rapportée au nombre de nouveaux clients sur la période. Le ratio LTV / CAC mesure la rentabilité de l'acquisition.", formula: "CAC = dépenses marketing + ventes ÷ nouveaux clients" },
  { slug: "signe-facture-encaisse", term: "Signé / facturé / encaissé", definition: "Les trois états successifs du revenu : signé dans le CRM, facturé dans l'outil de facturation, encaissé en banque. Leur réconciliation client par client révèle les fuites de revenus.", link: { href: "/reconciliation-crm-facturation", label: "Réconciliation CRM et facturation" } },
  { slug: "ecart-signe-facture", term: "Écart signé / facturé", definition: "Différence, par deal, entre le montant signé dans le CRM et le montant facturé. Toujours mesuré en valeur absolue (écart brut) : les écarts nets se compensent et masquent les erreurs.", formula: "Écart brut = Σ |montant du deal − montant facturé|" },
  { slug: "fuite-de-revenus", term: "Fuite de revenus (revenue leakage)", definition: "Revenu contractuellement gagné mais jamais facturé ou jamais encaissé, à cause de ruptures entre ventes, facturation et recouvrement. Estimée entre 1 et 5 % du chiffre d'affaires dans les études publiées.", link: { href: "/fuite-de-revenus", label: "Fuite de revenus" } },
  { slug: "reconciliation", term: "Réconciliation (rapprochement) CRM × facturation", definition: "Processus qui associe les deals signés aux factures émises et aux paiements reçus, après avoir reconnu qu'un même client existe dans chaque outil. Préalable à toute mesure fiable du revenu.", link: { href: "/reconciliation-crm-facturation", label: "Réconciliation CRM et facturation" } },
  { slug: "resolution-d-entites", term: "Résolution d'entités", aliases: ["entity resolution", "rapprochement des comptes"], definition: "Reconnaissance d'une même entreprise sous des noms ou identifiants différents dans plusieurs outils. En France, elle s'appuie sur le SIREN, le SIRET et le numéro de TVA intracommunautaire.", link: { href: "/produits/resolution-entites", label: "Résolution d'entités" } },
  { slug: "siren", term: "SIREN / SIRET", definition: "Identifiants légaux des entreprises françaises : le SIREN (9 chiffres) identifie l'entité juridique, le SIRET (14 chiffres) chacun de ses établissements. Attribués par l'INSEE et consultables via l'API Sirene, ils sont la clé la plus fiable pour rapprocher CRM et facturation." },
  { slug: "dso", term: "DSO (délai moyen de paiement)", aliases: ["Days Sales Outstanding"], definition: "Nombre de jours moyen entre l'émission d'une facture et son encaissement. Un DSO qui s'allonge signale un risque de trésorerie.", formula: "DSO = créances clients ÷ chiffre d'affaires × nombre de jours de la période" },
  { slug: "facture-en-retard", term: "Facture en retard (échue)", definition: "Facture dont la date d'échéance est dépassée et dont le montant dû est supérieur à zéro. Priorisée par montant pour la relance." },
  { slug: "projection-de-tresorerie", term: "Projection de trésorerie pondérée", definition: "Prévision des encaissements futurs combinant les factures à échoir, le forecast pondéré des deals et les délais de paiement observés par client." },
  { slug: "audit-crm", term: "Audit CRM", definition: "Mesure de la qualité des données du CRM : complétude des propriétés, doublons, contacts sans entreprise, deals sans montant ou sans date, deals stagnants. Préalable à un forecast fiable.", link: { href: "/audit-crm-hubspot", label: "Audit CRM HubSpot" } },
  { slug: "completude", term: "Taux de complétude", definition: "Part des enregistrements dont une propriété clé est renseignée (e-mail, entreprise, montant, date de fermeture…). Indicateur de qualité suivi comme un KPI." },
  { slug: "doublon", term: "Doublon CRM", definition: "Deux enregistrements décrivant le même contact ou la même entreprise. Détectés par e-mail, domaine, nom normalisé ou identifiant légal, puis fusionnés après validation." },
  { slug: "hierarchie-de-comptes", term: "Hiérarchie de comptes", definition: "Lien maison mère – filiales entre entreprises du CRM, reconstitué à partir des identifiants légaux. Permet de consolider le revenu d'un groupe." },
  { slug: "kpi-cable", term: "KPI câblé (vérifié)", definition: "Indicateur dont la définition (entité, dimension, mesure, période) a été recalculée sur les données réelles et validée avant d'être affiché ou suivi par une alerte. Principe de Revold : aucun chiffre non recalculable.", link: { href: "/tableau-de-bord-revops", label: "Tableau de bord RevOps" } },
  { slug: "alerte-de-seuil", term: "Alerte de seuil", definition: "Notification déclenchée quand un KPI franchit une valeur définie (au-dessus ou en dessous), détectée par un moteur déterministe et envoyée sur un canal (Slack, Teams, e-mail, SMS, WhatsApp)." },
  { slug: "brief-du-jour", term: "Brief du jour", definition: "Point de situation quotidien, par équipe, qui lit les exceptions et les échéances : alertes en tension, deals prêts à signer, factures en retard, objectifs atteints. Dans Revold, lu à voix haute par la tour de contrôle." },
  { slug: "source-unique-de-verite", term: "Source unique de vérité", aliases: ["single source of truth"], definition: "Référentiel dans lequel chaque donnée n'a qu'une origine reconnue. En RevOps : le CRM pour le signé, la facturation pour le facturé, la banque pour l'encaissé, et une plateforme qui les rapproche." },
  { slug: "geo", term: "GEO (Generative Engine Optimization)", definition: "Optimisation d'un site pour être compris et cité par les moteurs génératifs (ChatGPT, Claude, Perplexity, AI Overviews) : définitions claires, faits cohérents, données structurées, fichier llms.txt, robots ouverts aux robots IA." },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY.find((t) => t.slug === slug);
}
