/**
 * Catalog: team → category → KPIs for custom report builder.
 * KPI ids match exactly the keys produced by computeMetricValues() in report-kpis.ts.
 */

export type TeamId = "sales" | "marketing" | "cs" | "revops";

export const TEAMS: { id: TeamId; label: string; icon: string; description: string }[] = [
  { id: "sales", label: "Ventes", icon: "💼", description: "Pipeline, deals, closing" },
  { id: "marketing", label: "Marketing", icon: "📣", description: "Attribution, acquisition, lifecycle" },
  { id: "cs", label: "Customer Success", icon: "🤝", description: "Rétention, tickets, expansion" },
  { id: "revops", label: "Revenue / Finance", icon: "📊", description: "Revenue, forecast, data quality" },
];

export type CategoryDef = {
  id: string;
  label: string;
  icon: string;
  description: string;
  objectiveMetier: string;
  metrics: string[];
};

export const CATEGORIES_BY_TEAM: Record<TeamId, CategoryDef[]> = {
  sales: [
    {
      id: "sales_ca",
      label: "Chiffre d'affaires",
      icon: "💰",
      description: "Volume et montant du closing, deal moyen, évolution mensuelle.",
      objectiveMetier: "Piloter la croissance du CA signé et identifier les leviers de deal moyen.",
      metrics: [
        "CA réalisé Closed Won (€)",
        "CA total Closed Won par mois (€)",
        "Nb de deals Closed Won par mois",
        "Deal moyen Closed Won (€)",
        "Évolution vs mois précédent (%)",
        "CA Closed Won par pipeline (€)",
        "CA Closed Won par owner (€)",
        "Nb de deals Won par owner",
        "Deal moyen par owner (€)",
      ],
    },
    {
      id: "sales_pipeline",
      label: "Pipeline",
      icon: "🚀",
      description: "Santé du pipeline ouvert : volume, montants, concentration, deals bloqués.",
      objectiveMetier: "Détecter les zones de risque, équilibrer la charge, débloquer les deals stagnants.",
      metrics: [
        "Deals actifs par pipeline",
        "Montant actif par pipeline (€)",
        "Nb de deals par stage actuel",
        "Concentration du pipeline (%)",
        "Top owners — deals actifs",
        "Top owners — montant pipeline (€)",
        "Répartition pipeline par owner (€)",
        "Nb de deals sans owner",
        "Nb de deals stagnants (>30j même stage)",
        "Montant total des deals stagnants (€)",
        "Top 10 deals bloqués par montant",
        "Stage où les deals bloquent le plus",
      ],
    },
    {
      id: "sales_cycle",
      label: "Cycle de ventes",
      icon: "⏱️",
      description: "Vélocité du cycle : durée moyenne, goulots, comparaison par pipeline.",
      objectiveMetier: "Raccourcir le cycle en identifiant les étapes bloquantes et les pipelines les plus lents.",
      metrics: [
        "Cycle moyen global (jours)",
        "Cycle moyen par pipeline",
        "Stage le plus bloquant",
        "Temps par étape (hs_time_in_latest_deal_stage)",
        "Durée moyenne par étape (jours)",
        "Étapes les plus lentes (>21 jours)",
        "Deals won par pipeline",
      ],
    },
    {
      id: "sales_forecast",
      label: "Prévisions",
      icon: "🔮",
      description: "Forecast pondéré, écart vs réalisé, projection par owner et pipeline.",
      objectiveMetier: "Fiabiliser la prévision revenue pour le COMEX et anticiper les risques de miss.",
      metrics: [
        "Pipeline pondéré total (€)",
        "Pipeline pondéré par owner",
        "Pipeline pondéré par pipeline (€)",
        "Écart forecast vs réalisé (%)",
        "CA réalisé Closed Won (€)",
        "Taux de conversion global pipeline → Won",
      ],
    },
    {
      id: "sales_activity",
      label: "Activité commerciale",
      icon: "📞",
      description: "Volume d'appels, emails, meetings et leur impact sur le closing.",
      objectiveMetier: "Corréler l'effort commercial avec le closing et identifier les top performers.",
      metrics: [
        "Nb total d'appels par owner",
        "Nb total d'emails envoyés par owner",
        "Nb total de meetings par owner",
        "Ratio emails envoyés / reçus",
        "Nb d'appels par owner / jour",
        "Taux de connexion (décrochés / tentés)",
        "Nb moyen d'appels par deal gagné vs perdu",
        "% des deals won ayant eu un appel",
        "Deals avec meetings vs sans meetings",
        "CA pipeline avec meetings vs sans (€)",
        "Nb moyen de meetings par deal actif",
        "Deals won avec 3+ meetings",
      ],
    },
    {
      id: "sales_conversion",
      label: "Conversion & stages",
      icon: "🎯",
      description: "Taux de conversion entre stages, déperdition, évolution mensuelle.",
      objectiveMetier: "Identifier où les deals meurent et prioriser le coaching sur les étapes critiques.",
      metrics: [
        "Taux de conversion global pipeline → Won",
        "Taux de conversion entre chaque stage (%)",
        "Stage avec le plus de déperdition",
        "Évolution mensuelle des taux de conversion",
        "Taux de conversion par pipeline (%)",
      ],
    },
  ],

  marketing: [
    {
      id: "mkt_attribution",
      label: "Attribution",
      icon: "🎯",
      description: "Répartition des contacts, taux d'attribution, owners et équilibre de charge.",
      objectiveMetier: "Garantir qu'aucun contact acquis n'est oublié et équilibrer la charge entre équipes.",
      metrics: [
        "Nb de contacts par owner",
        "% de la base par owner",
        "Contacts sans owner (non attribués)",
        "% de contacts attribués par owner",
        "% de contacts orphelins",
        "Évolution mensuelle de l'attribution",
        "Nb de contacts orphelins (sans owner)",
      ],
    },
    {
      id: "mkt_lifecycle",
      label: "Lifecycle stage",
      icon: "🔄",
      description: "Répartition du cycle de vie, funnel Lead → Opportunity → Deal, blocages.",
      objectiveMetier: "Optimiser les transitions de phase et maximiser la conversion Lead → Opp → Deal.",
      metrics: [
        "Répartition par lifecycle stage",
        "Total contacts Lead",
        "Total contacts Opportunity",
        "Taux Lead → Opportunity (%)",
        "Lifecycle stage des contacts orphelins",
        "Taux de conversion contact → deal par source",
      ],
    },
    {
      id: "mkt_sources",
      label: "Tracking sources",
      icon: "📡",
      description: "Volume et performance par canal d'acquisition (offline, social, direct, organic).",
      objectiveMetier: "Prioriser les canaux performants et détecter une dépendance à un seul canal.",
      metrics: [
        "Contacts source Offline",
        "Contacts source Organic Search",
        "Contacts source Direct Traffic",
        "Contacts source Autres",
        "Nb de contacts source SOCIAL",
        "% des contacts totaux issus du social",
        "Nb de contacts créés par source outbound",
        "Taux de conversion contact → deal par source",
      ],
    },
    {
      id: "mkt_performance",
      label: "Performance marketing",
      icon: "📈",
      description: "Vélocité d'acquisition, tendances mensuelles, exploitabilité de la base.",
      objectiveMetier: "Mesurer la dynamique d'acquisition et la qualité exploitable de la base marketing.",
      metrics: [
        "Contacts créés par mois (tendance)",
        "Contacts créés ce mois",
        "Contacts créés mois précédent",
        "Variation mois vs mois (%)",
        "Deals créés par mois (tendance)",
        "Contacts avec email (%)",
        "Contacts avec téléphone (%)",
        "Contacts avec poste (%)",
        "Contacts rattachés à une entreprise (%)",
      ],
    },
    {
      id: "mkt_revenue_influence",
      label: "Influence sur le CA",
      icon: "💎",
      description: "CA généré par canal, ROI outbound/social, contribution marketing au revenue.",
      objectiveMetier: "Prouver le ROI revenue du marketing et justifier l'allocation budgétaire par canal.",
      metrics: [
        "CA total Closed Won issu de l'outbound (€)",
        "Nb de deals Closed Won par campagne",
        "Comparaison outbound vs inbound",
        "CA total Closed Won source SOCIAL (€)",
        "Nb de deals Won source SOCIAL",
        "Taille moyenne des deals SOCIAL vs autres sources",
        "Taux de conversion social → deal",
        "CA généré via contacts social (€)",
        "Cycle moyen des deals SOCIAL (jours)",
      ],
    },
  ],

  cs: [
    {
      id: "cs_retention",
      label: "Rétention & satisfaction",
      icon: "🛡️",
      description: "CSAT proxy, résolution tickets, taux de réouverture.",
      objectiveMetier: "Suivre la santé de la satisfaction client et prévenir les signaux d'insatisfaction.",
      metrics: [
        "Score CSAT proxy global (%)",
        "Taux de résolution au 1er contact (%)",
        "Taux de réouverture de tickets (%)",
        "Nb de tickets ouverts / fermés par période",
        "CSAT proxy par agent support",
        "Évolution mensuelle du CSAT proxy",
      ],
    },
    {
      id: "cs_tickets",
      label: "Tickets & support",
      icon: "🎟️",
      description: "Volume, priorité, canaux et répartition par pipeline support.",
      objectiveMetier: "Piloter la charge support et identifier les goulots de résolution.",
      metrics: [
        "Nb de tickets ouverts / fermés par période",
        "% de tickets haute priorité",
        "Tickets haute priorité ouverts",
        "Nb de tickets par canal",
        "Tickets par pipeline support",
        "CSAT proxy par agent support",
      ],
    },
    {
      id: "cs_risk",
      label: "Risque & churn",
      icon: "⚠️",
      description: "Comptes à risque, deals stagnants, contacts non rattachés.",
      objectiveMetier: "Détecter les signaux faibles de churn et activer un plan de rétention proactif.",
      metrics: [
        "Nb de deals stagnants (>30j même stage)",
        "Montant total des deals stagnants (€)",
        "Top 10 deals bloqués par montant",
        "Stage où les deals bloquent le plus",
        "Lifecycle stage des contacts orphelins",
        "% de deals orphelins par pipeline",
      ],
    },
    {
      id: "cs_expansion",
      label: "Expansion & upsell",
      icon: "📈",
      description: "Panier moyen, volume de renouvellements, deals Won par owner.",
      objectiveMetier: "Suivre la croissance organique par compte et prioriser les opportunités d'upsell.",
      metrics: [
        "Deal moyen Closed Won (€)",
        "CA réalisé Closed Won (€)",
        "Nb de deals Won par owner",
        "Deal moyen par owner (€)",
        "CA Closed Won par owner (€)",
      ],
    },
  ],

  revops: [
    {
      id: "revops_revenue",
      label: "Revenue & facturation",
      icon: "💶",
      description: "CA signé, CA facturé, écart CRM ↔ facturation, impayés.",
      objectiveMetier: "Fiabiliser le CA réel et identifier les écarts entre forecast CRM et facturation.",
      metrics: [
        "CA réalisé Closed Won (€)",
        "CA total Closed Won par mois (€)",
        "Montant total facturé (€)",
        "Montant total encaissé (€)",
        "Nb de factures en attente de paiement",
        "Montant total impayé (€)",
        "CA forecast HubSpot vs facturé réel (€)",
        "Écart moyen forecast vs facturé (%)",
        "Nb de factures impayées > 90 jours",
      ],
    },
    {
      id: "revops_forecast",
      label: "Forecast & projection",
      icon: "🔮",
      description: "Pipeline pondéré, écart forecast/réalisé, projection par owner et pipeline.",
      objectiveMetier: "Prévision data-driven pour le COMEX avec visibilité des risques de miss.",
      metrics: [
        "Pipeline pondéré total (€)",
        "Pipeline pondéré par owner",
        "Pipeline pondéré par pipeline (€)",
        "Écart forecast vs réalisé (%)",
        "CA réalisé Closed Won (€)",
        "CA Closed Won par pipeline (€)",
      ],
    },
    {
      id: "revops_data_quality",
      label: "Qualité de données",
      icon: "🔍",
      description: "Enrichissement par objet, orphelins, champs critiques manquants.",
      objectiveMetier: "Garantir la fiabilité des reportings et la capacité de segmentation fine.",
      metrics: [
        "Enrichissement Contacts (%)",
        "Enrichissement Entreprises (%)",
        "Enrichissement Transactions (%)",
        "Score global de qualité CRM (%)",
        "Nb de deals sans contact associé",
        "Nb de deals sans company associée",
        "Montant total des deals orphelins (€)",
        "% de deals orphelins par pipeline",
        "Nb de contacts sans company associée",
        "Champs les moins remplis (bottom 5)",
      ],
    },
    {
      id: "revops_mrr",
      label: "MRR / ARR / Churn",
      icon: "🔁",
      description: "Revenue récurrent, churn gross, taux de succès paiement.",
      objectiveMetier: "Suivre la santé du revenue récurrent et les risques de churn financier.",
      metrics: [
        "MRR total actuel (€)",
        "ARR extrapolé (€)",
        "Taux de churn gross (%)",
        "Nb de paiements réussis vs échoués",
        "Taux de succès global (%)",
        "Montant total en échec (€)",
      ],
    },
    {
      id: "revops_efficiency",
      label: "Efficacité process",
      icon: "⚙️",
      description: "Ratio deals créés/closés, pipeline net, vélocité process.",
      objectiveMetier: "Mesurer l'efficience du process commercial et anticiper les creux de pipeline.",
      metrics: [
        "Ratio créés / closés",
        "Pipeline net (créés - closés)",
        "Deals créés par mois (tendance)",
        "Deals won par mois (tendance)",
        "Cycle moyen global (jours)",
        "Taux de conversion global pipeline → Won",
      ],
    },
  ],
};

export function getCategory(teamId: TeamId, categoryId: string): CategoryDef | undefined {
  return CATEGORIES_BY_TEAM[teamId]?.find((c) => c.id === categoryId);
}
